### ISSUE TITLE
firmtool: Command not found

### ISSUE THREAD

**Issue by Takeda-man-do-code** [linux-3ds/firm_linux_loader#12]
No clue wtf I'm doing wrong here, I'm trying to compile it all, but this is the only thing stopping the 'firm_linux_loader.firm' file from being made
The full error:
firmtool build firm_linux_loader.firm -D arm9/firm_linux_loader_arm9.elf arm11/firm_linux_loader_arm11.elf -C NDMA XDMA -i
make: firmtool: Command not found
Makefile:11: recipe for target 'firm_linux_loader.firm' failed

**Comment by Wolfvak** [comment]
Check the install dependencies in https://github.com/linux-3ds/firm_linux_loader/wiki, you haven't installed firmtool

**Comment by Takeda-man-do-code** [comment]
> Check the install dependencies in https://github.com/linux-3ds/firm_linux_loader/wiki, you haven't installed firmtool

$ sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi
$ pip3 install -U git+https://github.com/TuxSH/firmtool.git

Yeah this? Installed both and I'm still getting the error, dont understand whats wrong.
error msg:

firmtool build firm_linux_loader.firm -D arm9/firm_linux_loader_arm9.elf arm11/firm_linux_loader_arm11.elf -C NDMA XDMA -i
make: firmtool: Command not found
Makefile:11: recipe for target 'firm_linux_loader.firm' failed
make: *** [firm_linux_loader.firm] Error 127

**Comment by Wolfvak** [comment]
Good to know it works?
