### ISSUE TITLE
Bug when booting

### ISSUE THREAD

**Issue by CharlesStudios** [linux-3ds/firm_linux_loader#21]
Hello, I'm trying to boot the Payload from Lumia, it shows black and white lines with multi-colored dots all down the screen and its on both of the screens, also, when any key pressed, it shuts down, please could someone help me.

**Comment by Wolfvak** [comment]
Are you 100% sure you set it up correctly? It sounds like it's failing to boot because you forgot to put in the kernel, arm9linuxfw or corresponding dtb file

**Comment by CharlesStudios** [comment]
> Are you 100% sure you set it up correctly? It sounds like it's failing to boot because you forgot to put in the kernel, arm9linuxfw or corresponding dtb file

I don't know, all the tutorial said to was to place the Firmware in the Payloads Folder

**Comment by Wolfvak** [comment]
You also need the kernel and arm9linuxfw installed, you can check their repos for more info.
