### ISSUE TITLE
How do this work?

### ISSUE THREAD

**Issue by danimesq** [linux-3ds/firm_linux_loader#34]
It may be too newbish from me, but I didn't see anything changing in my 3DS lol

How to run custom Bash scripts, for example?

@Wolfvak

**Comment by Wer-Wolf** [comment]
For running bash scripts, you first need to boot linux. This firm_linux_loader is basically a bootloader for the linux kernel, and is only active during boot. In order to run custom bash scripts, either create a customized rootfs using buildroot or use the shell for entering them.

**Comment by ParzivalWolfram** [comment]
You need the other components of the project, mainly a rootfs from Buildroot, and preferably, arm9linuxfw (though this isn't required.) There's not much going on yet, because the kernel drivers are incomplete.
