### ISSUE TITLE
booting other linux

### ISSUE THREAD

**Issue by dabao1955** [linux-3ds/firm_linux_loader#36]
Hello, sir.  
I want to boot other linux systems on 3ds instead of buildroot.  what should I do?  I tried replacing rootfs.cpio.gz and still booted to buildroot.

**Comment by ItsCOMMANDer** [comment]
for me, i hacked a hello world init arm32 little endian elf file together packaged it and it worked, but due to aa lack of linux os on my laptop and windows being not good for this stuff, has stoped me form going deeper. anyway.
tldr: you can, if you know how

**Comment by ParzivalWolfram** [comment]
> Hello, sir. I want to boot other linux systems on 3ds instead of buildroot. what should I do? I tried replacing rootfs.cpio.gz and still booted to buildroot.

The buildroot boot files are required, as we're not far enough into development yet to apply patches to other distros to boot them. If the kernel ever supports mpcore again, and if we can shore up drivers for whatever API changes happen from 5.10.x to then, we could theoretically get an actual distro running.
