### ISSUE TITLE
Firm Loader cant load files 16MiB or Larger

### ISSUE THREAD

**Issue by ItsCOMMANDer** [linux-3ds/firm_linux_loader#38]
I tired starting my own buildroot image but it wouldnt load, the screen just apears to freeze or not make any progress. so i tried a bit. A 8MiB file will be loaded in ~20 Seconds, but then trying to load a 16MiB file takes, well, idk. Its still loading after 10 Minutes. I hope this can get fixed.

**Comment by ItsCOMMANDer** [comment]
after some more testing, it cant handly ANYTHING more than 8 MiB or 8192 KiB, 8193 KiB doesnt load anymore.

**Comment by ParzivalWolfram** [comment]
This is actually due to a hardcoded limit in [the kernel config](https://github.com/linux-3ds/linux/blob/7071ec29fd3ebd55d00a70cb6482e98d4702c5f2/arch/arm/boot/dts/nintendo3ds_ctr.dts#L42-L43), I plan on reworking this soon as it's getting in the way of kernel development as well.

**Comment by ItsCOMMANDer** [comment]
i am a bit confused, that is the kernel config, but the linux_firm_loader cant load it? is it also hardcoded in firm_loader?

**Comment by ParzivalWolfram** [comment]
> i am a bit confused, that is the kernel config, but the linux_firm_loader cant load it? is it also hardcoded in firm_loader?

[Yes, for now.](https://github.com/linux-3ds/firm_linux_loader/blob/ecb0f0d5a8d8aaafaf5edca279098b52ecfa71a0/common/linux_config.h#L2-L7)

**Comment by ItsCOMMANDer** [comment]
Oh, imma close tbis "ussie" than, have a great day!
